# Generated by Django 5.1.15 on 2026-05-12 01:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agents', '__first__'),
        ('issues', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=16)),
                ('creator_id', models.UUIDField()),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('work_dir', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('unread_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='agents.agent')),
                ('daemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='accounts.daemon')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='issues.issue')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.workspace')),
            ],
            options={
                'db_table': 'chat_session',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='agents.task')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['workspace'], name='idx_chat_session_workspace'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['creator_id', 'workspace'], name='idx_chat_session_creator'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='idx_chat_message_session'),
        ),
    ]
