# Generated by Django 5.1.15 on 2026-05-11 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('lead_type', models.CharField(blank=True, choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20, null=True)),
                ('lead_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.workspace')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='project_workspa_3df1f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_ref', models.JSONField()),
                ('label', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
            options={
                'db_table': 'project_resource',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['project', 'resource_type'], name='project_res_project_5b7683_idx'), models.Index(fields=['workspace_id'], name='project_res_workspa_e048ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'resource_type', 'resource_ref'), name='project_resource_unique_ref')],
            },
        ),
    ]
