# Generated by Django 5.1.15 on 2026-05-12 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('actor_id', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.workspace')),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='idx_activity_ws_created'), models.Index(fields=['issue_id', 'created_at'], name='idx_activity_issue_created')],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('recipient_id', models.UUIDField()),
                ('actor_type', models.CharField(blank=True, choices=[('member', 'Member'), ('agent', 'Agent'), ('system', 'System')], max_length=20, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('issue_assigned', 'Issue Assigned'), ('unassigned', 'Unassigned'), ('assignee_changed', 'Assignee Changed'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('due_date_changed', 'Due Date Changed'), ('new_comment', 'New Comment'), ('mentioned', 'Mentioned'), ('review_requested', 'Review Requested'), ('task_completed', 'Task Completed'), ('task_failed', 'Task Failed'), ('agent_blocked', 'Agent Blocked'), ('agent_completed', 'Agent Completed'), ('reaction_added', 'Reaction Added'), ('quick_create_done', 'Quick Create Done'), ('quick_create_failed', 'Quick Create Failed')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('issue_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='accounts.workspace')),
            ],
            options={
                'db_table': 'inbox_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id', 'read'], name='idx_inbox_recipient'), models.Index(fields=['workspace', 'created_at'], name='idx_inbox_ws_created')],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('issue', 'Issue'), ('project', 'Project')], max_length=20)),
                ('item_id', models.UUIDField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='accounts.workspace')),
            ],
            options={
                'db_table': 'pinned_item',
                'ordering': ['position', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'item_type', 'item_id', 'pinned_by'), name='pin_workspace_item_user_unique')],
            },
        ),
    ]
