# Generated by Django 5.1.15 on 2026-05-12 01:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agents', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autopilot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('execution_mode', models.CharField(choices=[('create_issue', 'Create Issue'), ('run_only', 'Run Only')], default='create_issue', max_length=20)),
                ('issue_title_template', models.CharField(blank=True, default='', max_length=500)),
                ('created_by_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=16)),
                ('created_by_id', models.UUIDField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilots', to='agents.agent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilots', to='accounts.workspace')),
            ],
            options={
                'db_table': 'autopilot',
            },
        ),
        migrations.CreateModel(
            name='AutopilotTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('schedule', 'Schedule'), ('webhook', 'Webhook'), ('api', 'API')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_token', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('autopilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='autopilots.autopilot')),
            ],
            options={
                'db_table': 'autopilot_trigger',
            },
        ),
        migrations.CreateModel(
            name='AutopilotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('schedule', 'Schedule'), ('webhook', 'Webhook'), ('api', 'API'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('issue_created', 'Issue Created'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='issue_created', max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('trigger_payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('autopilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='autopilots.autopilot')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='issues.issue')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='agents.task')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='autopilots.autopilottrigger')),
            ],
            options={
                'db_table': 'autopilot_run',
            },
        ),
        migrations.AddIndex(
            model_name='autopilot',
            index=models.Index(fields=['workspace', 'status'], name='autopilot_workspa_b77653_idx'),
        ),
    ]
