# Generated by Django 5.1.15 on 2026-05-12 01:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUsageDailyDirty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField()),
            ],
            options={
                'db_table': 'task_usage_daily_dirty',
            },
        ),
        migrations.CreateModel(
            name='TaskUsageRollupState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'task_usage_rollup_state',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(choices=[('claude', 'Claude'), ('codex', 'Codex'), ('copilot', 'Copilot'), ('openclaw', 'OpenClaw'), ('opencode', 'OpenCode'), ('hermes', 'Hermes'), ('gemini', 'Gemini'), ('pi', 'Pi'), ('cursor', 'Cursor'), ('kimi', 'Kimi'), ('kiro', 'Kiro')], max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('max_concurrent_tasks', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('visibility', models.CharField(choices=[('workspace', 'Workspace'), ('private', 'Private')], default='workspace', max_length=20)),
                ('custom_env', models.JSONField(blank=True, default=dict)),
                ('custom_args', models.JSONField(blank=True, default=dict)),
                ('mcp_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.daemon')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.workspace')),
            ],
            options={
                'db_table': 'agent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.workspace')),
            ],
            options={
                'db_table': 'skill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to='agents.agent')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to='agents.skill')),
            ],
            options={
                'db_table': 'agent_skill',
            },
        ),
        migrations.CreateModel(
            name='SkillFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='agents.skill')),
            ],
            options={
                'db_table': 'skill_file',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('work_dir', models.CharField(blank=True, default='', max_length=500)),
                ('attempt', models.IntegerField(default=1)),
                ('max_attempts', models.IntegerField(default=1)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('trigger_summary', models.CharField(blank=True, default='', max_length=255)),
                ('autopilot_run_id', models.UUIDField(blank=True, null=True)),
                ('force_fresh_session', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.agent')),
                ('daemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.daemon')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='issues.issue')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tasks', to='agents.task')),
                ('trigger_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_tasks', to='issues.comment')),
            ],
            options={
                'db_table': 'agent_task_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('tool_use', 'Tool Use'), ('tool_result', 'Tool Result'), ('error', 'Error'), ('thinking', 'Thinking'), ('status', 'Status')], max_length=20)),
                ('tool', models.CharField(blank=True, default='', max_length=100)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.task')),
            ],
            options={
                'db_table': 'task_message',
                'ordering': ['task', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='TaskUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=255)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cache_read_tokens', models.IntegerField(default=0)),
                ('cache_write_tokens', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='agents.task')),
            ],
            options={
                'db_table': 'task_usage',
            },
        ),
        migrations.CreateModel(
            name='TaskUsageDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=255)),
                ('bucket_date', models.DateField()),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cache_read_tokens', models.IntegerField(default=0)),
                ('total_cache_write_tokens', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='agents.agent')),
                ('daemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='accounts.daemon')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='accounts.workspace')),
            ],
            options={
                'db_table': 'task_usage_daily',
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workspace'], name='agent_workspa_7a7314_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['daemon'], name='agent_daemon__0d464c_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='agent_workspace_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='skill_workspace_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='agentskill',
            constraint=models.UniqueConstraint(fields=('agent', 'skill'), name='agent_skill_agent_skill_unique'),
        ),
        migrations.AddConstraint(
            model_name='skillfile',
            constraint=models.UniqueConstraint(fields=('skill', 'path'), name='skill_file_skill_path_unique'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['daemon', 'status'], name='agent_task__daemon__904a78_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['agent', 'status'], name='agent_task__agent_i_c1a6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmessage',
            index=models.Index(fields=['task', 'seq'], name='task_messag_task_id_7986b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskusage',
            constraint=models.UniqueConstraint(fields=('task', 'provider', 'model'), name='task_usage_task_provider_model_unique'),
        ),
        migrations.AddConstraint(
            model_name='taskusagedaily',
            constraint=models.UniqueConstraint(fields=('workspace', 'daemon', 'provider', 'model', 'bucket_date'), name='task_usage_daily_unique'),
        ),
    ]
