# Generated by Django 5.1.15 on 2026-05-12 01:14

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('in_review', 'In review'), ('done', 'Done'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='backlog', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20)),
                ('assignee_type', models.CharField(blank=True, choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20, null=True)),
                ('assignee_id', models.UUIDField(blank=True, null=True)),
                ('creator_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('creator_id', models.UUIDField()),
                ('origin_type', models.CharField(blank=True, choices=[('autopilot', 'Autopilot'), ('quick_create', 'Quick create')], max_length=20, null=True)),
                ('origin_id', models.UUIDField(blank=True, null=True)),
                ('first_executed_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.FloatField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='issues.issue')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.workspace')),
            ],
            options={
                'db_table': 'issue',
                'ordering': ['workspace', 'position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('author_id', models.UUIDField()),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status change'), ('system', 'System'), ('progress_update', 'Progress update')], default='comment', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_type', models.CharField(blank=True, choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20, null=True)),
                ('resolved_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='issues.comment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.workspace')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('uploader_id', models.UUIDField()),
                ('url', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.comment')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
            ],
            options={
                'db_table': 'attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('blocks', 'Blocks'), ('blocked_by', 'Blocked by'), ('related', 'Related')], max_length=20)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='issues.issue')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_dependency',
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='accounts.workspace')),
            ],
            options={
                'db_table': 'issue_label',
            },
        ),
        migrations.CreateModel(
            name='IssueReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('actor_id', models.UUIDField()),
                ('emoji', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_reaction',
            },
        ),
        migrations.CreateModel(
            name='IssueSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('subscriber_id', models.UUIDField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_subscriber',
            },
        ),
        migrations.CreateModel(
            name='IssueToLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issuelabel')),
            ],
            options={
                'db_table': 'issue_to_label',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('member', 'Member'), ('agent', 'Agent')], max_length=20)),
                ('actor_id', models.UUIDField()),
                ('emoji', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='issues.comment')),
            ],
            options={
                'db_table': 'comment_reaction',
                'constraints': [models.UniqueConstraint(fields=('comment', 'actor_type', 'actor_id', 'emoji'), name='uq_comment_reaction')],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['workspace', 'status'], name='issue_workspa_b54541_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assignee_type', 'assignee_id'], name='issue_assigne_dd1846_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['parent_issue'], name='issue_parent__6aa7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project'], name='issue_project_5d9c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['origin_type', 'origin_id'], name='issue_origin__ef28e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='uq_issue_workspace_number'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['issue', 'created_at'], name='comment_issue_i_bba397_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['issue', 'resolved_at'], name='comment_issue_i_faf7c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('issue__isnull', False), ('comment__isnull', False), _connector='OR'), name='attachment_target_check'),
        ),
        migrations.AddConstraint(
            model_name='issuelabel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='issue_label_workspace_name_lower_unique'),
        ),
        migrations.AddConstraint(
            model_name='issuereaction',
            constraint=models.UniqueConstraint(fields=('issue', 'actor_type', 'actor_id', 'emoji'), name='uq_issue_reaction'),
        ),
        migrations.AddConstraint(
            model_name='issuesubscriber',
            constraint=models.UniqueConstraint(fields=('issue', 'subscriber_type', 'subscriber_id'), name='uq_issue_subscriber'),
        ),
        migrations.AddConstraint(
            model_name='issuetolabel',
            constraint=models.UniqueConstraint(fields=('issue', 'label'), name='issue_to_label_pkey'),
        ),
    ]
